name: Deploy HTML and Test

on:
    push:
        branches:
            - main

jobs:
    build-deploy:
        runs-on: ubuntu-latest

        permissions:
            pages: write
            id-token: write

        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        # Déploiement via GitHub Pages
        - name: Setup Pages
          uses: actions/configure-pages@v5

        - name: Upload artifact
          uses: actions/upload-pages-artifact@v3
          with:
            path: .

        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4

    test:
        runs-on: ubuntu-latest
        needs: build-deploy

        steps:
            - name : Tester mon appli
              run: |
                sleep 10 # attendre un peu le déploiement
                RESPONSE=$(curl -s "https://ezyinfo.github.io/githubactions/test.html" | tr -d '\n' | xargs)
                if [ "$RESPONSE" != "OK" ]; then
                    echo "La page ne renvoie pas OK mais: $RESPONSE"
                    exit 1
                fi
                echo "Page OK ✅"

